version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network
      
  nuxt:
    build: ./path/to/nuxt
    container_name: my-nuxt
    volumes:
      - ./path/to/nuxt:/app
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - redis
      - postgres


volumes:
  postgres-data:

networks:
  my-network:
    external: true
